name: Run Tests

on: 
  pull_request:
  push:
    - branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *' 

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses:  gradle/gradle-build-action@v2
        with:
          arguments: test
      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: app/build/test-results/**/*.xml
      - name: Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests Report           
          path: app/build/test-results/**/*.xml    
          reporter: java-junit
          fail-on-error: false
      - name: Upload Tests Summary
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-summary
          path: app/build/reports/
