name: Run Tests

on: 
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *' 

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses:  gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: app/build/test-results/**/*.xml
          output: test-summary.md
        if: always()
      - name: Upload Test Summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-summary.md
        if: always()
      - name: Upload Tests Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-reports
          path: app/build/reports/
